version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./foodgram/.env
  web:
    build: .
    restart: always
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./foodgram/.env
  nginx:
    image: nginx:1.19.4
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./static:/usr/share/nginx/html/static:ro
      - ./media:/usr/share/nginx/html/media:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    env_file:
      - ./foodgram/.env
  certbot:
    image: certbot/certbot:v1.7.0
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 34h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
